// novel-editor-vue/src/components/selectors/NodeSelector.vue
<script setup lang="ts">
import { computed } from "vue";
import { type Editor } from "@tiptap/vue-3";
import { Check, ChevronDown, Heading1, Heading2, Heading3, Type } from "lucide-vue-next";
import Button from "../ui/Button.vue";
import Dropdown from "../ui/Dropdown.vue";

interface NodeSelectorProps {
  editor: Editor;
  open: boolean;
}

const props = defineProps<NodeSelectorProps>();

const emit = defineEmits<{
  (e: "update:open", value: boolean): void;
}>();

const items = [
  {
    name: "Text",
    icon: Type,
    command: (editor: Editor) => editor.chain().focus().clearNodes().run(),
    isActive: (editor: Editor) => editor.isActive("paragraph"),
  },
  {
    name: "Heading 1",
    icon: Heading1,
    command: (editor: Editor) => editor.chain().focus().clearNodes().toggleHeading({ level: 1 }).run(),
    isActive: (editor: Editor) => editor.isActive("heading", { level: 1 }),
  },
  {
    name: "Heading 2",
    icon: Heading2,
    command: (editor: Editor) => editor.chain().focus().clearNodes().toggleHeading({ level: 2 }).run(),
    isActive: (editor: Editor) => editor.isActive("heading", { level: 2 }),
  },
  {
    name: "Heading 3",
    icon: Heading3,
    command: (editor: Editor) => editor.chain().focus().clearNodes().toggleHeading({ level: 3 }).run(),
    isActive: (editor: Editor) => editor.isActive("heading", { level: 3 }),
  },
];

const activeItem = computed(() => {
  return items.find((item) => item.isActive(props.editor)) ?? { name: "Multiple" };
});

const handleOpenChange = (val: boolean) => {
  emit("update:open", val);
};

const selectItem = (item: typeof items[number]) => {
  item.command(props.editor);
  emit("update:open", false);
};
</script>

<template>
  <Dropdown :open="open" @update:open="handleOpenChange" align="start">
    <template #trigger>
      <Button
        size="sm"
        variant="ghost"
        class="gap-2 rounded-none border-none hover:bg-accent focus:ring-0"
        @click="handleOpenChange(!open)"
      >
        <span class="whitespace-nowrap text-sm">{{ activeItem.name }}</span>
        <ChevronDown class="h-4 w-4" />
      </Button>
    </template>

    <template #content>
      <div class="w-48 p-1 flex flex-col">
        <button
          v-for="item in items"
          :key="item.name"
          type="button"
          class="flex w-full cursor-pointer items-center justify-between rounded-sm px-2 py-1.5 text-sm text-left hover:bg-accent focus:outline-none"
          @click="selectItem(item)"
        >
          <div class="flex items-center space-x-2">
            <div class="rounded-sm border p-1 bg-background">
              <component :is="item.icon" class="h-3.5 w-3.5" />
            </div>
            <span>{{ item.name }}</span>
          </div>
          <Check v-if="activeItem.name === item.name" class="h-4 w-4 text-primary" />
        </button>
      </div>
    </template>
  </Dropdown>
</template>

// src/components/tailwind/selectors/node-selector.tsx
import {
  Check,
  ChevronDown,
  Heading1,
  Heading2,
  Heading3,
  type LucideIcon,
  TextIcon,
} from "lucide-react";
import { type EditorInstance, EditorBubbleItem, useEditor } from "@/lib/novel";

import { Button } from "@/components/tailwind/ui/button";
import { PopoverContent, PopoverTrigger } from "@/components/tailwind/ui/popover";
import { Popover } from "@radix-ui/react-popover";

export type SelectorItem = {
  name: string;
  icon: LucideIcon;
  command: (editor: EditorInstance) => void;
  isActive: (editor: EditorInstance) => boolean;
};

const items: SelectorItem[] = [
  {
    name: "Text",
    icon: TextIcon,
    command: (editor) => editor.chain().focus().clearNodes().run(),
    isActive: (editor) => editor.isActive("paragraph"),
  },
  {
    name: "Heading 1",
    icon: Heading1,
    command: (editor) => editor.chain().focus().clearNodes().toggleHeading({ level: 1 }).run(),
    isActive: (editor) => editor.isActive("heading", { level: 1 }),
  },
  {
    name: "Heading 2",
    icon: Heading2,
    command: (editor) => editor.chain().focus().clearNodes().toggleHeading({ level: 2 }).run(),
    isActive: (editor) => editor.isActive("heading", { level: 2 }),
  },
  {
    name: "Heading 3",
    icon: Heading3,
    command: (editor) => editor.chain().focus().clearNodes().toggleHeading({ level: 3 }).run(),
    isActive: (editor) => editor.isActive("heading", { level: 3 }),
  },
];
interface NodeSelectorProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export const NodeSelector = ({ open, onOpenChange }: NodeSelectorProps) => {
  const { editor } = useEditor();
  if (!editor) return null;
  const activeItem = items.filter((item) => item.isActive(editor)).pop() ?? {
    name: "Multiple",
  };

  return (
    <Popover modal={true} open={open} onOpenChange={onOpenChange}>
      <PopoverTrigger asChild className="gap-2 rounded-none border-none hover:bg-accent focus:ring-0">
        <Button size="sm" variant="ghost" className="gap-2">
          <span className="whitespace-nowrap text-sm">{activeItem.name}</span>
          <ChevronDown className="h-4 w-4" />
        </Button>
      </PopoverTrigger>
      <PopoverContent sideOffset={5} align="start" className="w-48 p-1">
        {items.map((item) => (
          <EditorBubbleItem
            key={item.name}
            onSelect={(editor) => {
              item.command(editor);
              onOpenChange(false);
            }}
            className="flex cursor-pointer items-center justify-between rounded-sm px-2 py-1 text-sm hover:bg-accent"
          >
            <div className="flex items-center space-x-2">
              <div className="rounded-sm border p-1">
                <item.icon className="h-3 w-3" />
              </div>
              <span>{item.name}</span>
            </div>
            {activeItem.name === item.name && <Check className="h-4 w-4" />}
          </EditorBubbleItem>
        ))}
      </PopoverContent>
    </Popover>
  );
};
